name: 编译

on:
  push:

env:
  TZ: Asia/Shanghai

jobs:
  主机清理:
    runs-on: ubuntu-latest
    # container:
    #   image: ubuntu:22.04
    env:
      TZ: Asia/Shanghai
      FORCE_UNSAFE_CONFIGURE: 1
      DEBIAN_FRONTEND: noninteractive
      # volumes:
      #   - /data:/data
    steps:
    - name: 初始化的环境
      run: |
        pwd
        id
        df -h

    - name: 移除各种大目录
      run: |
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/hostedtoolcache
        df -h

  容器执行:
    needs: 主机清理
    runs-on: ubuntu-latest
    containers:
      image: ubuntu:20.04
        
    steps:
    - name: 安装ttyshare
      run: |
        sudo apt update -y
        sudo apt install -y wget
        sudo wget --no-check-certificate 'https://github.com/elisescu/tty-share/releases/download/v2.4.1/tty-share_linux-amd64' -O /bin/tty-share
        sudo chmod +x /bin/tty-share

    # - name: Setup TTY Faker
    #   uses: achrinza/github-actions-tty-faker@main

    - name: 配置反向链接
      shell: 'script -q -e -c "bash {0}"'
      run: |
        stty sane
        stty cols 120 rows 40
        tty-share --public
